### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#10]
Parameters in Configuration Files
---

Use the parameters section of a config file to set parameters:

```yaml
parameters:
    mailer.transport: sendmail
```

You can refer to parameters elsewhere in any config file by surrounding them with percent (%) signs, e.g. %mailer.transport%.

```yaml
parameters:
    mailer.transport: sendmail

services:
    app.mailer:
        class:     ./App/Mailer
        arguments: ['%mailer.transport%']
```

Getting and Setting Container Parameters in JavaScript
---

Working with container parameters is straightforward using the container's accessor methods for parameters:

```js
import {ContainerBuilder} from 'node-dependency-injection'
let container = new ContainerBuilder()

if (container.hasParameter('mailer.transport')) {
    // ...
}

let mailerTransport = container.getParameter('mailer.transport')

// add a new parameter
container.setParameter('mailer.transport', 'sendmail')
```

Array Parameters
---

Parameters do not need to be flat strings, they can also contain array values.
For example
```yaml
parameters:
    my_mailer.gateways: [mail1, mail2, mail3]

    my_multilang.language_fallback:
        en:
            - en
            - fr
        fr:
            - fr
            - en
```
