### ISSUE TITLE
Support named exports at the file configuration

### ISSUE THREAD

**Issue by vilasmaciel** [zazoomauro/node-dependency-injection#128]
Hi! 

We are building a project using Typescript, and we are facing problems using named exports at our classes, let me show it with an example:

If I define a controller like this:

```ts
export class UserController {
}
``` 

And I try to use it with the `yaml` configuration:

```yml
  App.infrastructure.UserController:
    class: ../infrastructure/UserController
    arguments: []
```
 

It fails because it's not able to find the class. 

We understand the it only works with `default` exports. Are you aware of that? Is there any workaround for working with named exports?
