### ISSUE TITLE
Adding TagReference as argument programmatically

### ISSUE THREAD

**Issue by cjuega** [zazoomauro/node-dependency-injection#155]
Hey this library is just awesome!

I'm in a serverless environment so I opted for managing the container programmatically (so webpack prunes any file which isn't really needed by my functions). I'll give yml files a try anyway. But this was the easiest setup.

Anyhow, the thing is, I'm trying to replicate something similar to the following example (from the wiki):

```yml
services:
  repository-manager:
    class: ./../RepositoryManager
    arguments: ["!tagged repository"]

  repository-foo:
    class: ./../RepositoryFoo
    tags:
      - { name: repository }
  
  repository-bar:
    class: ./../RepositoryBar
    tags:
      - { name: repository }
```

I believe the code must look like:

```ts
    let definition = new Definition(RepositoryFoo);
    definition.addTag('repository')
    container.setDefinition('repository-foo', definition);

    definition = new Definition(RepositoryBar);
    definition.addTag('repository')
    container.setDefinition('repository-bar', definition);

    container.register('repository-manager', RepositoryManager).addArgument(new TagReference('repository'));
```

The problem with the code above is that `TagReference` class isn't exported, so I haven't access to it. Is there any other way to achieve the same result without exporting `TagReference`?
