### ISSUE TITLE
Binding Arguments by Name or Type for defaults

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#175]
Bind keyword to bind specific arguments by name or type:

or in pure js or typescript

```ts
const compiler = new ContainerBuilder(false, '../path/to/src')
const autowire = new Autowire(compiler)
autowire.addBind('adminEmail', 'manager@example.com')
autowire.addBind('someParameter', process.env.SOME_PARAMETER)
```

or in yaml

```yaml
services:
    _defaults:
        bind:
            # pass this value to any adminEmail argument for any service
            # that's defined in this file (including controller arguments)
            adminEmail: 'manager@example.com'

            # also if is coming from environment variables
           someParameter: ['%env(SOME_PARAMETER)%']
```

Then you can use it it that way

```ts
export default class SomeService() {
  constructor(
    private readonly adminEmail: string,
    private readonly someParameter: string,
  ) {}
}
```
