### ISSUE TITLE
Exclude a list of folders from Autowire

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#178]
Exclude some specific folders in order to avoid autowiring from root directory

```ts
const container = new ContainerBuilder(false, '/path/to/src')
const autowire = new Autowire(container)
autowire.addExclude('/models') ## the excluded folder is /path/to/src/models
autowire.addExclude('../models') ## throw an error because folder is not inside path/to/src/
autowire.addExclude('models/entities') ## ## the excluded folder is /path/to/src/models/entities
```

from service file configuration 

```yaml
services:
  _defaults:
    autowire: true
    rootDir: "/path/to/src"
    exclude: ["/models", "models/entities"]
```
