### ISSUE TITLE
Require of ES Module not supported

### ISSUE THREAD

**Issue by AntonKrychevskyy** [zazoomauro/node-dependency-injection#183]
Have small educational example for initial exploration of DI. 

```js
import * as path from 'path';
import { fileURLToPath } from 'url';
import { ContainerBuilder, YamlFileLoader } from 'node-dependency-injection';

console.log('Hello, this is Homework #06');

const container = new ContainerBuilder();
const loader = new YamlFileLoader(container);
const configPath = path.join(path.dirname(fileURLToPath(import.meta.url)), 'config.yml');
await loader.load(configPath);

container.get('car').start();
```

```yaml
services:
    car:
        class: ./car
        arguments: ['Mercedes', 'SLS AMG', '@dieselEngine', '2022']
    dieselEngine:
        class: ./diesel-engine
        arguments: []
        calls:
            - { method: 'setHp', arguments: ['600'] }
```
Don't think there is any sense to put here other files content.

It fails when I run `node src/app.js` due to services are imported with `require()` statement.

```bash
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/anton/Projects/patterns-js/patterns/lesson_06/homework_06/src/car.js from /Users/anton/Projects/patterns-js/patterns/lesson_06/homework_06/node_modules/node-dependency-injection/dist/lib/Loader/FileLoader.js not supported.
Instead change the require of car.js in /Users/anton/Projects/patterns-js/patterns/lesson_06/homework_06/node_modules/node-dependency-injection/dist/lib/Loader/FileLoader.js to a dynamic import() which is available in all CommonJS modules.
```

If I change all files from ES modules to CommonJS, and remove `"type": "module"` in package.json all works fine. But it is disappointing cause your docs full of examples written as ES modules.
