### ISSUE TITLE
Aliasing

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#2]
Aliasing
-------
You may sometimes want to use shortcuts to access some services.

```js
container.setAlias('mailer', 'app.mailer')
```

or

```yaml
services:
    app.mailer:
        class: ./Mailer

    mailer: '@app.mailer'
```

This means that when using the container directly, you can access the _app.mailer_ service by asking for the _mailer_ service like this:

```js
let mailer = container.get('mailer')
```
