### ISSUE TITLE
Enable main property for factory

### ISSUE THREAD

**Issue by coal182** [zazoomauro/node-dependency-injection#200]
The `main` property in a service definition allows to specify a main class into a file specified by a path in the class property. This is helpful when the filename doesn't match with the service class, for example when using kebab-case for filenames.

```yml
Shop.Shared.MongoConfig:
    factory:
      class: ../../../../../contexts/shop/shared/infrastructure/persistence/mongo/mongo-config-factory
      main: MongoConfigFactory
      method: 'createConfig'
```

Factories definitions doesn't handle the main property at the moment.
Since main property is not available for factory (instead of service). Would be possible to add it here?

https://github.com/zazoomauro/node-dependency-injection/blob/cfe270e218d7c6523d08360fc75af5f844687b34/lib/Loader/FileLoader.js#L97

to look like:
```javascript
object = this._requireClassNameFromPath(service.factory.class, service.factory.main) 
```

Thanks in advance.
