### ISSUE TITLE
Autowiring override arguments do not work when compiled on file

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#219]
```
services:
  App.FooBarAutowireOverride:
    class: ''
    arguments: []
    abstract: false
  App.AnotherFooBarAutowireOverride:
    class: ''
    arguments: []
    abstract: false
```
when overriding class is empty when dump file
