### ISSUE TITLE
Configure a Service with a Configurator

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#26]
The service configurator is a feature of the service container that allows you to use a callable to configure a service after its instantiation.

A service configurator can be used, for example, when you have a service that requires complex setup based on configuration settings coming from different sources/services. Using an external configurator, you can maintain the service implementation cleanly and keep it decoupled from the other objects that provide the configuration needed.

Another use case is when you have multiple objects that share a common configuration or that should be configured in a similar way at runtime.

For example, suppose you have an application where you send different types of emails to users. Emails are passed through different formatters that could be enabled or not depending on some dynamic application settings. You start defining a NewsletterManager class like this:

```js
class NewsletterManager {
    setEnabledFormatters(enabledFormatters) {
        this.enabledFormatters = enabledFormatters
    }

    // ...
}
```
and also a GreetingCardManager class:
```js
class GreetingCardManager {
    setEnabledFormatters(enabledFormatters) {
        this.enabledFormatters = enabledFormatters
    }

    // ...
}
```

As mentioned before, the goal is to set the formatters at runtime depending on application settings. To do this, you also have an EmailFormatterManager class which is responsible for loading and validating formatters enabled in the application:

```js
class EmailFormatterManager {

    // ...

    getEnabledFormatters() {
        // code to configure which formatters to use
        let enabledFormatters = [...]

        // ...

        return enabledFormatters
    }
}
```

If your goal is to avoid having to couple NewsletterManager and GreetingCardManager with EmailFormatterManager, then you might want to create a configurator class to configure these instances:

```js
class EmailConfigurator {
    /**
     * @param  {EmailFormatterManager} formatterManager
     */
    constructor(formatterManager) {
        this.formatterManager = formatterManager
    }

    configure(emailManager) {
        emailManager.setEnabledFormatters(this.formatterManager.getEnabledFormatters())
    }

    // ...
}
```

The EmailConfigurator's job is to inject the enabled formatters into NewsletterManager and GreetingCardManager because they are not aware of where the enabled formatters come from. On the other hand, the EmailFormatterManager holds the knowledge about the enabled formatters and how to load them, keeping the single responsibility principle.

You can configure the service configurator using the configurator option:

```js
container.register('app.email_formatter_manager', EmailFormatterManager)
container
  .register('app.email_configurator', EmailConfigurator)
  .addArgument(new Reference('app.email_formatter_manager'))

container
  .register('app.newsletter_manager', NewsletterManager)
  .addArgument(new Reference('mailer'))
  .setConfigurator(new Reference('app.email_configurator'), 'configure')

container
  .register('app.greeting_card_manager', GreetingCardManager);
  .addArgument(new Reference('mailer'))
  .setConfigurator(new Reference('app.email_configurator'), 'configure')
```

###### YAML
```yaml
services:
    app.email_formatter_manager:
        class: ./EmailFormatterManager

    app.email_configurator:
        class:     ./App/Mail/EmailConfigurator
        arguments: ['@app.email_formatter_manager']

    app.newsletter_manager:
        class:        ./App/Mail/NewsletterManager
        arguments:    ['@mailer']
        configurator: ['@app.email_configurator', configure]

    app.greeting_card_manager:
        class:        ./App/Mail/GreetingCardManager
        arguments:    ['@mailer']
        configurator: ['@app.email_configurator', configure]
```

###### JSON
```json
{
	"services": {
		"app.email_formatter_manager": {
			"class": "./EmailFormatterManager"
		},
		"app.email_configurator": {
			"class": "./App/Mail/EmailConfigurator",
			"arguments": [
				"@app.email_formatter_manager"
			]
		},
		"app.newsletter_manager": {
			"class": "./App/Mail/NewsletterManager",
			"arguments": [
				"@mailer"
			],
			"configurator": [
				"@app.email_configurator",
				"configure"
			]
		},
		"app.greeting_card_manager": {
			"class": "./App/Mail/GreetingCardManager",
			"arguments": [
				"@mailer"
			],
			"configurator": [
				"@app.email_configurator",
				"configure"
			]
		}
	}
}
```

When requesting the app.newsletter_manager or app.greeting_card_manager service, the created instance will first be passed to the `EmailConfigurator.configure()` method
