### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#3]
How to Work with Service Tags
-------------------------------

In the service container, a tag implies that the service is meant to be used for a specific purpose. Take the following example:

```js
import {Definition, ContainerBuilder} from 'node-dependency-injection'
import FileRepository from './Entity/Repository/FileRepository'

let definition = new Definition(FileRepository)
definition.addTag('repository')

container.setDefinition('app.entity.file_repository', definition)
```
or
```yaml
services:
    app.entity.file_repository:
        class: ./Entity/Repository/FileRepository
        tags:
            - { name: repository }
```

You can now use a compiler pass to ask the container for any services with the repository tag. Example:

```js
class RepositoryPass {
    process (container) {
        taggedServices = container.findTaggedServiceIds('repository');

        foreach (let [id, definition] of taggedServices) {
            // ...
        }
    }
}
```
