### ISSUE TITLE
Using a Factory to Create Services

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#4]
Using a Factory to Create Services
-----------------------------------
Suppose you have a factory that configures and returns a new NewsletterManager object:

```js
import NewsletterManager from './NewsletterManager'

class NewsletterManagerFactory {
    static createNewsletterManager() {
        let newsletterManager = new NewsletterManager()

        // ...

        return newsletterManager
    }
}
```

To make the NewsletterManager object available as a service, you can configure the service container to use the NewsletterManagerFactory.createNewsletterManager() factory method:

###### YAML
```yaml
services:
    # call a static method
    app.newsletter_manager:
        factory: 
          class: './App/Email/NewsletterManager'
          method: 'createNewsletterManager'

    # OR

    # call a method on the specified service
    app.newsletter_manager_factory:
        class: ./App/Email/NewsletterManagerFactory

    app.newsletter_manager:
        factory:
          class: '@app.newsletter_manager_factory'
          method: 'createNewsletterManager'      
```

###### JS
```js
let definition = new Definition()
definition.setFactory(NewsletterManagerFactory, 'createNewsletterManager')
container.setDefinition('app.newsletter_manager', definition)

// or

let definitionFactory = new Definition(NewsletterManagerFactory)
container.setDefinition('app.newsletter_manager_factory', definitionFactory)

let definition = new Definition()
definition.setFactory(new Reference('app.newsletter_manager_factory'), 'createNewsletterManager')
container.setDefinition('app.newsletter_manager', definition)
```

You can also send some arguments to the static method if needed

###### YAML
```yaml
services:
    app.newsletter_manager:
        arguments: ['simple_string', '@another_service', '%package_reference']
        factory: 
          class: './App/Email/NewsletterManager'
          method: 'createNewsletterManager'
```

###### JS
```js
let definition = new Definition()
definition.args = ['simple_string', new Reference('another_service'), new PackageReference('package_reference')]
definition.setFactory(NewsletterManagerFactory, 'createNewsletterManager')
container.setDefinition('app.newsletter_manager', definition)
```
