### ISSUE TITLE
Adding Additional Attributes on Tags

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#40]
Sometimes you need additional information about each service that's tagged with your tag.
For example, you might want to add an event to each listener.

To begin with, change the services configuration file:

###### YAML
```yaml
services:
    app.listener.user_listener:
        class: ./Listener/UserListener
        tags:
              - {name: listener, attributes: {event: postUpdate}}
    
    app.listener.account_listener:
        class: ./Listener/AccountListener
        tags:
              - {name: listener, attributes: {event: prePersist}}
```

###### JS

```js
let definition = new Definition(SomeObject)
let attributes = new Map()
attributes.set('event', 'prePersist')
definition.addTag('listener', attributes)
container.setDefinition('app.listener', definition)
```

Notice that you've added a generic event key to the tag. 
To actually use this, update the compiler:

```js
class ListenerPass {
    /**
     * @param {ContainerBuilder} container
     */
    process (container) {
       let taggedServices = container.findTaggedServiceIds('listener')
       
       for (let definition of taggedServices.values()) {
         for (let tag of definition.tags) {
           definition.addMethodCall(tag.attributes.get('event'))
         }
       }
    }
}
```

The double loop may be confusing. This is because a service can have more than one tag. You tag a service twice or more with the `listener` tag. The second for loop iterates over the `listener ` tags set for the current service and gives you one tag object.
