### ISSUE TITLE
How to Define Non Shared Services

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#45]
In the service container, all services are shared by default. This means that each time you retrieve the service, you'll get the same instance. This is often the behaviour you want, but in some cases, you might want to always get a new instance.

In order to always get a new instance, set the shared setting to false in your service definition:

###### YAML
```yaml
services:
    app.some_not_shared_service:
        class: ...
        shared: false
        # ...
```

###### JS
```js
import {Definition} from 'node-dependency-injection'

let definition = new Definition(...)
definition.shared = false

container.setDefinition('app.some_not_shared_service', definition)
```

Now, whenever you call `container.get('app.some_not_shared_service')` or inject this service, you'll receive a new instance.
