### ISSUE TITLE
How to Decorate Services

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#46]
This configuration replaces `app.mailer` with a new one, but keeps a reference of the old one as `app.decorating_mailer.inner`:

###### YAML
```yaml
services:
    app.mailer:
        class: ./AppBundle/Mailer

    app.decorating_mailer:
      class: ./AppBundle/DecoratingMailer
      decorates: app.mailer
      arguments: ['@app.decorating_mailer.inner']
      public: false
```

###### JS
```js
import DecoratingMailer from './DecoratingMailer'
import {Reference} from 'node-dependency-injection'

let definition = container.register('app.decorating_mailer', DecoratingMailer)
definition.decoratedService = 'app.mailer'
definition.addArgument(new Reference('app.decorating_mailer.inner'))
definition.public = false
```

Here is what's going on here: the decorates option tells the container that the `app.decorating_mailer` service replaces the app.mailer service. By convention, the old app.mailer service is renamed to `app.decorating_mailer.inner`, so you can inject it into your new service.

Most of the time, the decorator should be declared private, as you will not need to retrieve it as `app.decorating_mailer` from the container.

The visibility of the decorated `app.mailer` service (which is an alias for the new service) will still be the same as the original `app.mailer` visibility.

The generated code will be the following:

```js
let mailerService = new DecoratingMailer(new Mailer()));
```
