### ISSUE TITLE
Decoration Priority

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#47]
If you want to apply more than one decorator to a service, you can control their order by configuring the priority of decoration, this can be any integer number (decorators with higher priorities will be applied first).

###### YAML
```yaml
services:
  foo:
      class: Foo
  
  bar:
      class: Bar
      public: false
      decorates: foo
      decoration_priority: 5
      arguments: ['@bar.inner']
  
  baz:
      class: Baz
      public: false
      decorates: foo
      decoration_priority: 1
      arguments: ['@baz.inner']
```

###### JS
```js
import {Reference} from 'node-dependency-injection';

container.register('foo', Foo)

let definition = container.register('bar', Bar)
definition.addArgument(new Reference('bar.inner'))
definition.public = false
definition.decoratedService = 'foo'
definition.decorationPriority = 5

let definition = container.register('baz', Baz)
definition.addArgument(new Reference('baz.inner'))
definition.public= false
definition.decoratedService = 'foo'
definition.decorationPriority = 1
```

The generated code will be the following:

```js
let fooService = new Baz(new Bar(new Foo())));
```
