### ISSUE TITLE
How to Manage Common Dependencies with Parent Services

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#48]
As you add more functionality to your application, you may well start to have related classes that share some of the same dependencies. For example, you may have multiple repository classes which need some manager service and an optional logger service:

```js
class BaseRepository {
  constructor (someManager, logger) {
    this._entityManager = someManager
    this._logger = logger
  }
}
```

Just as you use inheritance to avoid duplication in your code, the service container allows you to extend parent services in order to avoid duplicated service definitions:

###### YAML
```yaml
services:
    app.base_repository:
        # as no class is configured, the parent service MUST be abstract
        abstract:  true
        arguments: ['@some_manager', '@logger']

    app.user_repository:
        class:  ./App/Repository/UserRepository
        parent: app.base_repository

    app.post_repository:
        class:  ./App/Repository/PostRepository
        parent: app.base_repository

    # ...
```

###### JS
```js
import UserRepository from './App/Repository/UserRepository'
import PostRepository from './App/Repository/PostRepository'
import {Reference, DefinitionDecorator} from 'node-dependency-injection'

container.register('app.base_repository')
  .addArgument(new Reference('some_manager'))
  .addArgument(new Reference('logger'))

let definition = new DefinitionDecorator('app.base_repository')
definition.Object = UserRepository
container.setDefinition('app.user_repository', definition)

let definition = new DefinitionDecorator('app.base_repository')
definition.Object = PostRepository
container.setDefinition('app.post_repository', definition)
// ...
```

In this context, having a parent service implies that the arguments and method calls of the parent service should be used for the child services. Specifically, SomeManager and Logger will be injected.
