### ISSUE TITLE
Passing Arguments to the Factory Method

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#5]
Passing Arguments to the Factory Method
-------
If you need to pass arguments to the factory method, you can use the arguments options inside the service container. 

```yaml
services:
    # ...

    app.newsletter_manager:
        class:     ./App/Email/NewsletterManager
        factory:   'newsletter_manager_factory:createNewsletterManager'
        arguments: ['@templating']
```
