### ISSUE TITLE
Lazy Services

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#6]
Lazy Services
---

In some cases, you may want to inject a service that is a bit heavy to instantiate, but is not always used inside your object. Configuring lazy services is one answer to this. With a lazy service the container builder will instantiate the service only when we need it (during the container builder _get_ call method)

```yaml
services:
   app.mailer:
     class: ./App/Mailer
     lazy:  true
```
The actual class will be instantiated as soon as you try to interact with the service (e.g. call one of its methods).
