### ISSUE TITLE
How to get required name in factory method?

### ISSUE THREAD

**Issue by popovserhii** [zazoomauro/node-dependency-injection#61]
I want to create something like to Abstract Factory and I need a required name. 
I check arguments but this was empty. Is there any possibility to get a required name in the factory method?

**Comment by zazoomauro** [comment]
@popovserhii Sorry for the delay in replying
Can u please provide me some code example?

**Comment by zazoomauro** [comment]
@popovserhii 🏓

**Comment by popovserhii** [comment]
Hello,
I want to have one factory for several objects which allow me to create a new object on a required name without passing extra arguments.
Now I create object with next config
```
module.exports = {
  services: {
    scraper: {
      arguments: ['@container', 'scraper/source/scraper'],
      factory: {
        class: '@coreManagerFactory',
        method: 'create',
      }
    },
  }
};
```
here my `@coreManagerFactory`
```
class CoreManagerFactory {
  static create(container, name) {
    let Manager = require(name);
    let manager = new Manager(config, factory);

    return manager;
  }
}
```
`'scraper/source/scraper'` is abandonment and will be good if name of service `scraper` will be passed automatically

**Comment by zazoomauro** [comment]
ok! now I get it...

If you need to pass arguments to the factory method, you can use the arguments options inside the service container.
like:
```yaml
services:
    # ...

    app.newsletter_manager:
        factory:
          class: '@coreManagerFactory'
          method: create
        arguments: ['some argument']
```
