### ISSUE TITLE
Property Injection

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#7]
Property Injection
---

Another possibility is just setting public fields of the class directly:
```js
class NewsletterManager {
     /**
      * @param {Mailer} mailer
      */
     set mailer (value) {
          this._mailer = value
     }
}
```
```yaml
services:
     # ...

     app.newsletter_manager:
         class: ./App/Mail/NewsletterManager
         properties:
             mailer: '@mailer'
```
