### ISSUE TITLE
Unable to load private npm packages

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#72]
If you have a private library and you want to inject it in to your class that is currently impossible because of `@`

```yaml
services:
  foo:
    class: ./../bar
    arguments: ['%@company/repository']
```

Response:
```
The service @company/repository is not registered
```
