### ISSUE TITLE
How to Import Configuration Files/Resources

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#8]
Importing Configuration with imports
---
If your application ends up having many services, this file becomes huge and hard to maintain. To avoid this, you can split your service configuration into multiple service files:

For example:

```yaml
# app/config/services/mailer.yml

services:
    app.mailer:
        class:        ./App/Mailer
        arguments:    ['mail_transport']
```

The definition itself hasn't changed, only its location. To make the service container load the definitions in this resource file, use the imports key in any already loaded resource

###### YAML
```yaml
# app/config/services.yml
imports:
    - { resource: services/mailer.yml }
    - { resource: services/another.yml }
```

###### JSON
```json
{
  "imports": [
    {"resource": "services/mailer.json"},
    {"resource": "services/another.json"}
  ]
}
```
###### JS
```js
module.exports = {
  imports: [
    {resource: 'services/mailer.js'},
    {resource: 'services/another.js'}
  ]
}
```
