### ISSUE TITLE
How to register config parameters

### ISSUE THREAD

**Issue by alberto-leon-crespo** [zazoomauro/node-dependency-injection#83]
I load a cnfig service yaml file. I have a instance to ContainerBuilder and i need to register config params before load yamel file. When i compile container y and put in my services.yaml file references to config params y get undefined. I register service like this:

```yml
services:
    bbdd.service:
        class: '../../dist/services/bbdd.service'
        arguments: ["%BBDD_HOST%","%BBDD_USER%","%BBDD_PASSWORD%","%BBDD_SCHEMA%","%BBDD_PORT%","%BBDD_DRIVER%"]
```

And i prepare container like this;
```typescript
private loadDependencyInjection(){
        let container = new ContainerBuilder();
        let loader = new YamlFileLoader(container);
        for(let key of Object.keys(process.env)){
            container.setParameter(null, key, process.env[key]);
        }
        loader.load(this.fixRoute + '/config/services.yaml');
        container.compile();
        this.container = container;
}
```
What is wromg?
