### ISSUE TITLE
Ignoring Missing Dependencies

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#9]
Ignoring Missing Dependencies
---

The behavior of ignoring missing dependencies is the same as the "null" behavior except when used within a method call, in which case the method call itself will be removed.

In the following example the container will inject a service using a method call if the service exists and remove the method call if it does not:

###### YAML
```yaml
services:
    app.newsletter_manager:
        class:     ./App/Newsletter/NewsletterManager
        calls:
            - [setMailer, ['@?app.mailer']]
```

###### JSON
```json
{
	"services": {
		"app.newsletter_manager": {
			"class": "./App/Newsletter/NewsletterManager",
			"calls": [
				[
					"setMailer",
					[
						"@?app.mailer"
					]
				]
			]
		}
	}
}
```

In YAML or JSON, the special @? syntax tells the service container that the dependency is optional. Of course, the NewsletterManager must also be rewritten by adding a setMailer() method:

```js
class NewsletterManager { 
    /*
     * @param {Mailer|null} mailer
     */
    setMailer(mailer = null) {
        // ...
    }
}
```
